name: graph
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda
  - numcodecs
  - pandas
  - pip
  - pyg
  - python
  - pytorch
  - pytorch-cluster
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-spline-conv
  - scikit-learn
  - scipy
  - torchvision
  - tqdm
  - xarray
  - zarr
  - h3-py
  - numpy
  - pyshtools
  - gcsfs
  - pytest
  - pip:
      - datasets
      - einops
      - fsspec
      - torch-geometric-temporal
      - huggingface-hub
      - pysolar
      - pytorch-lightning
      - click
      - trimesh
      - rtree
      - torch-harmonics
